### ISSUE TITLE
Why the builder generate nullable types fields for not nullable type fields?

### ISSUE THREAD

**Issue by elect86** [F43nd1r/autodsl#47]
First of all, super cool project, this is something I wanted to write myself, but I didn't have enough skills for that :p

Anyway, as titled, why AutoDsl generated for  `class Person(val name: String)` a builder with the `name` field as `String?` instead of `String`?

**Comment by F43nd1r** [comment]
When the builder is created, no value for `name` is known. The builder field is initially null and that is reflected in the type.

**Comment by elect86** [comment]
What about using `lateinit`?

**Comment by F43nd1r** [comment]
I guess that is a question of style. In my opinion public lateinit fields just make it easier to write code that breaks

**Comment by elect86** [comment]
> I guess that is a question of style. 

It could be. But on the other side, it's coherent with the underlying object to build. Also, since the field is mandatory, it does fit perfectly the logic of `lateinit`, since the field is not supposed to be (left) `null`, but initialized (at least once)

(and it still can be checked with `::name.isInitialized`

**Comment by F43nd1r** [comment]
I don't see value in that, and it makes problems in implementation, e.g. primitive values can't be lateinit.

Do you have an example where this would improve something beyond personal preference?

**Comment by elect86** [comment]
Primitives shall be initialized to their default value, as in Java, `0`

This looks simply weird, it caught my eye at the very first example I was experimenting with
